SKILL_MATCH_WEIGHT = 0.30
CAREER_ALIGNMENT_WEIGHT = 0.20
INTEREST_MATCH_WEIGHT = 0.15
LOCATION_MATCH_WEIGHT = 0.10
EDUCATION_ELIGIBILITY_WEIGHT = 0.10
PREFERENCE_MATCH_WEIGHT = 0.10
READINESS_WEIGHT = 0.05
READINESS_SKILL_WEIGHT = 0.50
READINESS_CERTIFICATE_WEIGHT = 0.20
READINESS_SENIORITY_WEIGHT = 0.30

APPLY_NOW_THRESHOLD = 80
APPLY_UPSKILL_THRESHOLD = 60

SEMANTIC_MATCH_THRESHOLD = 0.65
SEMANTIC_MATCH_CREDIT = 0.6
