SKILL_MATCH_WEIGHT = 0.30
CAREER_ALIGNMENT_WEIGHT = 0.20
INTEREST_MATCH_WEIGHT = 0.15
LOCATION_MATCH_WEIGHT = 0.10
EDUCATION_ELIGIBILITY_WEIGHT = 0.10
PREFERENCE_MATCH_WEIGHT = 0.10
READINESS_WEIGHT = 0.05

APPLY_NOW_THRESHOLD = 80
APPLY_UPSKILL_THRESHOLD = 60
