"""add recommendation explanation text

Revision ID: 3b83150ce9e9
Revises: 5c9c50b4498e
Create Date: 2026-09-20 14:12:08.337349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b83150ce9e9'
down_revision: Union[str, Sequence[str], None] = '5c9c50b4498e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('explanation_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'explanation_text')
    # ### end Alembic commands ###
