"""add semantic embedding columns

Revision ID: 5c9c50b4498e
Revises: c41c50160655
Create Date: 2026-09-20 11:31:18.519660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9c50b4498e'
down_revision: Union[str, Sequence[str], None] = 'c41c50160655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('description_embedding', sa.JSON(), nullable=True))
    op.add_column('skills', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'embedding')
    op.drop_column('internships', 'description_embedding')
    # ### end Alembic commands ###
