"""add student recommendation profile fields

Revision ID: c41c50160655
Revises: f38a5dad19db
Create Date: 2026-09-20 11:12:29.682490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41c50160655'
down_revision: Union[str, Sequence[str], None] = 'f38a5dad19db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('students', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'preferences')
    op.drop_column('students', 'interests')
    # ### end Alembic commands ###
